In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()

In [4]:
sonar_df = pd.read_csv("/content/sonar data.csv", header = None)

In [5]:
sonar_df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [6]:
sonar_df.shape

(208, 61)

In [7]:
sonar_df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [8]:
# Column names
sonar_df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [9]:
sonar_df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [10]:
# Splitting features and Target

X = sonar_df.drop(60, axis = 1)
Y = sonar_df[60]

In [11]:
print(X)
print(Y)

         0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      50      51      52      53   

In [13]:
# Convert the Y, Target set from text to numerical form
# Use get_dummies method and drop the 1st column out of it

Y = pd.get_dummies(Y, drop_first=True)
Y
# R --> 1, M --> 0

R
0    1
1    1
2    1
3    1
4    1
..  ..
203  0
204  0
205  0
206  0
207  0

[208 rows x 1 columns]

## **Model Building**

In [17]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

In [15]:
# Split into Train and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [16]:
X.shape, X_train.shape, X_test.shape

((208, 60), (166, 60), (42, 60))

In [21]:
# Model Building
model = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation = 'relu'),
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dense(1,activation = 'sigmoid')
])

#compile the model
model.compile(
    optimizer='adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

# training the model
model.fit(X_train, Y_train, epochs = 100, batch_size=8)

Epoch 1/100
21/21 [==============================] - 1s 3ms/step - loss: 0.6872 - accuracy: 0.5482
Epoch 2/100
21/21 [==============================] - 0s 2ms/step - loss: 0.6510 - accuracy: 0.5904
Epoch 3/100
21/21 [==============================] - 0s 2ms/step - loss: 0.6162 - accuracy: 0.6747
Epoch 4/100
21/21 [==============================] - 0s 3ms/step - loss: 0.5721 - accuracy: 0.7530
Epoch 5/100
21/21 [==============================] - 0s 3ms/step - loss: 0.5177 - accuracy: 0.7651
Epoch 6/100
21/21 [==============================] - 0s 3ms/step - loss: 0.4700 - accuracy: 0.8133
Epoch 7/100
21/21 [==============================] - 0s 2ms/step - loss: 0.4446 - accuracy: 0.7892
Epoch 8/100
21/21 [==============================] - 0s 2ms/step - loss: 0.4365 - accuracy: 0.8012
Epoch 9/100
21/21 [==============================] - 0s 2ms/step - loss: 0.4338 - accuracy: 0.7771
Epoch 10/100
21/21 [==============================] - 0s 2ms/step - loss: 0.3933 - accuracy: 0.8012
Epoch 11/

In [22]:
# test data evaluation
model.evaluate(X_test, Y_test)

2/2 [==============================] - 0s 14ms/step - loss: 1.4145 - accuracy: 0.7381


[1.4144806861877441, 0.738095223903656]

Model Gives 100% accuracy with training data but the accuracy score for test data is only 73% that means the model is overfitted

In [25]:
# Prediction
Y_pred = model.predict(X_test).reshape(-1)
print(Y_pred[:10])

# Round of the values to nearest 0 or 1
Y_pred = np.round(Y_pred)
Y_pred[:10]

2/2 [==============================] - 0s 9ms/step
[2.8928155e-09 9.8825747e-01 3.6939514e-01 1.2240502e-06 9.9999976e-01
 9.7281259e-01 4.2022737e-03 9.9999845e-01 3.0751203e-06 9.9999988e-01]


array([0., 1., 0., 0., 1., 1., 0., 1., 0., 1.], dtype=float32)

In [26]:
Y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [27]:
# Getting Classification report
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.68      0.85      0.76        20
           1       0.82      0.64      0.72        22

    accuracy                           0.74        42
   macro avg       0.75      0.74      0.74        42
weighted avg       0.76      0.74      0.74        42



# **Model with Dropout Layer**

In [29]:
# Model Building
model1 = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation = 'relu'),
    keras.layers.Dropout(0.5), # drop 50% of neuron from the layer
    keras.layers.Dense(30, activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(20, activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation = 'sigmoid')
])

#compile the model
model1.compile(
    optimizer='adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

# training the model
model1.fit(X_train, Y_train, epochs = 100, batch_size=8)

Epoch 1/100
21/21 [==============================] - 3s 4ms/step - loss: 0.7059 - accuracy: 0.5542
Epoch 2/100
21/21 [==============================] - 0s 3ms/step - loss: 0.7293 - accuracy: 0.4759
Epoch 3/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6997 - accuracy: 0.5602
Epoch 4/100
21/21 [==============================] - 0s 3ms/step - loss: 0.7005 - accuracy: 0.4940
Epoch 5/100
21/21 [==============================] - 0s 3ms/step - loss: 0.7010 - accuracy: 0.5000
Epoch 6/100
21/21 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.5843
Epoch 7/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6959 - accuracy: 0.5663
Epoch 8/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6891 - accuracy: 0.5301
Epoch 9/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6792 - accuracy: 0.5723
Epoch 10/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6636 - accuracy: 0.5964
Epoch 11/

In [30]:
model1.evaluate(X_test, Y_test)

2/2 [==============================] - 0s 13ms/step - loss: 0.5205 - accuracy: 0.8095


[0.5204684734344482, 0.8095238208770752]

Here we can see that the accuracy score for both test data and training data is almost similar. That means the dropout regularization handled the overfitting very well.

In [31]:
# Prediction
Y_pred1 = model1.predict(X_test).reshape(-1)
print(Y_pred[:10])

# Round of the values to nearest 0 or 1
Y_pred1 = np.round(Y_pred1)
Y_pred1[:10]

2/2 [==============================] - 0s 8ms/step
[0. 1. 0. 0. 1. 1. 0. 1. 0. 1.]


array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1.], dtype=float32)

In [33]:
print(classification_report(Y_test, Y_pred1))

              precision    recall  f1-score   support

           0       0.77      0.85      0.81        20
           1       0.85      0.77      0.81        22

    accuracy                           0.81        42
   macro avg       0.81      0.81      0.81        42
weighted avg       0.81      0.81      0.81        42

